# Generated by Django 4.2.2 on 2023-06-10 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='equipes',
            field=models.ManyToManyField(through='core.VeiculoEquipe', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.cliente'),
        ),
    ]
