# Generated by Django 4.2.2 on 2023-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='os',
        ),
        migrations.AddField(
            model_name='os',
            name='item',
            field=models.ManyToManyField(related_name='os', to='core.item'),
        ),
    ]
